---
title: "Lab11_LewisCheng"
author: "Lewis Cheng"
date: "`r Sys.Date()`"
output: html_document
---

#Q1
```{r}
library("tidyverse") #library stuff
library("quanteda")
library("quanteda.textplots")
tweetDF <- data.frame(read_csv(url("https://ist387.s3.us-east-2.amazonaws.com/lab/ClimatePosts.csv"))) #get data
str(tweetDF) #look at data
```

#Q2
```{r}
tweetCorpus <- corpus(tweetDF$Tweet, docnames=tweetDF$ID) #make a quanteda corpus object to use in quanteda
```

#Q3
```{r}
tweetDFM <- dfm(tweetCorpus, remove_punct=TRUE, 
                                  remove=stopwords("english"), ) #make a DFM

```
#Q4
```{r}
#seems that it lists out topics and words that are relevant in them
```

#Q5
```{r}
textplot_wordcloud(tweetDFM, min_count = 1) #make a wordcloud!
```
#Q6
```{r}
m <- as.matrix(tweetDFM)
postCounts <- rowSums(m)
tweetDF$postCounts <- postCounts 
boxplot(postCounts ~ Skeptic, data=tweetDF)  #creates a box plot of post counts of skeptics vs non skeptics

```
#Q7
```{r}
URL <- "https://ist387.s3.us-east-2.amazonaws.com/data/positive-words.txt"
posWords <- scan(URL, character(0), sep = "\n") #read in the positive words

badURL <- "https://ist387.s3.us-east-2.amazonaws.com/data/negative-words.txt"
negWords <- scan(badURL, character(0), sep = "\n") # read in the negative owrds


```

#Q8
```{r}
wordCounts <- colSums(m) #count all them words
wordCounts <- sort(wordCounts, decreasing=TRUE) #sort all the word ocuts

```

#Q9
```{r}
str(wordCounts) #take a look
head(wordCounts)
```

#Q10
```{r}
matchedP <- match(names(wordCounts), posWords, nomatch = 0)  #match for positive owrds
```

#Q11
```{r}
matchedP
sum(matchedP != 0) #number of matched positive words
```

#Q12
```{r}
matchedN <- match(names(wordCounts), negWords, nomatch = 0) 
sum(matchedN != 0)
matchedN #number of matched negative words + matches

```





